apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
  labels:
    app: picalc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picalc
  template:
    metadata:
      labels:
        app: picalc
    spec:
      serviceAccountName: tekton
      containers:
        - name: picalc
          image: __IMAGE__
          ports:
            - containerPort: 80
          volumeMounts:
            - name: aws-secret
              mountPath: /root/.aws/
            - name: docker-config
              mountPath: /kaniko/.docker/
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
        - name: docker-config
          configMap:
            name: docker-config
