apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
  labels:
    app: picalc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picalc
  template:
    metadata:
      labels:
        app: picalc
    spec:
      containers:
        - name: picalc
          image: __IMAGE__
          ports:
            - containerPort: 80
